import type { Metadata } from "next";
import { Montserrat, Lato } from "next/font/google";
import "./globals.css";
import Header from "@/components/layout/Header";
import Footer from "@/components/layout/Footer";
// 2. Configure the fonts (weights and subsets)
const montserrat = Montserrat({
  subsets: ["latin"],
  variable: "--font-montserrat", // Creates a CSS variable we can use in Tailwind
});

const lato = Lato({
  subsets: ["latin"],
  weight: ["400", "700"], // Lato requires specific weights
  variable: "--font-lato",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${montserrat.variable} ${lato.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
